version: '3.8'
name: laravel
services:
  php:
    build:
      dockerfile: Dockerfile
      args:
        user: Neptune
        uid: 1000
        project_name: MyLaravelApp
    depends_on:
      - db
    volumes:
      - ../:/var/www/html/
    ports:
      - 8000:8000
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: gg
    ports:
      - 3306:3306
